using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Rewired;
using TangledeepAccess.Util;

namespace TangledeepAccess.Controls
{
    /// <summary>
    /// Writes a full control listing to a text file by reading the game's own
    /// Rewired data, so it is authoritative for this install. Covers:
    ///   1. Current bindings  - what the player actually presses right now (active
    ///      keyboard layout + any connected controller; reflects rebinds).
    ///   2. Keyboard layouts  - the Default and WASD layout defaults, side by side,
    ///      so a player can compare/choose.
    ///   3. Gamepad defaults  - default controller bindings when one is connected.
    ///
    /// All real input flows through Rewired as named actions (player.GetButton
    /// ("Wait Turn"), etc.); the legacy InputMapper/TDControl KeyCode path is
    /// vestigial. This reads the Rewired action + map model directly.
    /// </summary>
    internal static class ControlDumper
    {
        /// <summary>
        /// Build the listing and write it to <paramref name="outputDir"/>. Returns
        /// the full file path. Requires <c>ReInput.isReady</c>.
        /// </summary>
        public static string Dump(string outputDir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("Tangledeep controls");
            sb.AppendLine("Generated by Tangledeep Access from the game's live Rewired data.");
            sb.AppendLine("Time: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine();
            sb.AppendLine(
                "Notes: an action can have more than one binding (listed comma-separated)."
            );
            sb.AppendLine(
                "Movement is split into axes; [Positive]/[Negative] marks the direction a key drives."
            );
            sb.AppendLine();

            Player player = ReInput.players.GetPlayer(0);

            // 1. Current effective bindings across the player's loaded maps.
            sb.AppendLine(
                "=== Current bindings (active keyboard layout + connected controller) ==="
            );
            WriteActions(sb, id => player.controllers.maps.ElementMapsWithAction(id, true));
            sb.AppendLine();

            // 2. Keyboard layout defaults (Default, WASD, ...). Empty category/layout
            //    combinations (the game leaves some map categories unused) are skipped.
            sb.AppendLine("=== Keyboard layouts (defaults) ===");
            IList<InputLayout> keyboardLayouts = ReInput.mapping.MapLayouts(
                ControllerType.Keyboard
            );
            foreach (InputMapCategory cat in ReInput.mapping.MapCategories)
            {
                if (!cat.userAssignable)
                    continue;
                foreach (InputLayout layout in keyboardLayouts)
                {
                    KeyboardMap km = ReInput.mapping.GetKeyboardMapInstance(cat.id, layout.id);
                    if (km == null)
                        continue;
                    AppendMap(
                        sb,
                        "--- " + Label(cat) + " / " + layout.name + " ---",
                        id => km.ElementMapsWithAction(id, true)
                    );
                }
            }

            // 3. Gamepad defaults (only resolvable with a controller connected).
            sb.AppendLine("=== Gamepad (defaults) ===");
            if (ReInput.controllers.joystickCount > 0)
            {
                Joystick joystick = ReInput.controllers.Joysticks[0];
                sb.AppendLine("Controller: " + joystick.name);
                IList<InputLayout> padLayouts = ReInput.mapping.MapLayouts(ControllerType.Joystick);
                foreach (InputMapCategory cat in ReInput.mapping.MapCategories)
                {
                    if (!cat.userAssignable)
                        continue;
                    foreach (InputLayout layout in padLayouts)
                    {
                        JoystickMap jm = ReInput.mapping.GetJoystickMapInstance(
                            joystick,
                            cat.id,
                            layout.id
                        );
                        if (jm == null)
                            continue;
                        AppendMap(
                            sb,
                            "--- " + Label(cat) + " / " + layout.name + " ---",
                            id => jm.ElementMapsWithAction(id, true)
                        );
                    }
                }
            }
            else
            {
                sb.AppendLine(
                    "No controller connected; reconnect one and re-dump for gamepad bindings."
                );
                sb.AppendLine();
            }

            string path = Path.Combine(outputDir, "tangledeep-controls.txt");
            File.WriteAllText(path, sb.ToString());
            return path;
        }

        /// <summary>
        /// Append a header + its action lines, but only if the map actually binds
        /// something (skips the game's empty map categories).
        /// </summary>
        private static void AppendMap(
            StringBuilder sb,
            string header,
            Func<int, IEnumerable<ActionElementMap>> lookup
        )
        {
            var body = new StringBuilder();
            if (WriteActions(body, lookup) == 0)
                return;
            sb.AppendLine(header);
            sb.Append(body);
            sb.AppendLine();
        }

        /// <summary>
        /// Emit one line per user-assignable action that has any binding from
        /// <paramref name="lookup"/>, in Rewired's authored action order. Returns the
        /// number of actions written.
        /// </summary>
        private static int WriteActions(
            StringBuilder sb,
            Func<int, IEnumerable<ActionElementMap>> lookup
        )
        {
            int written = 0;
            foreach (InputAction action in ReInput.mapping.UserAssignableActions)
            {
                var parts = new List<string>();
                foreach (ActionElementMap aem in lookup(action.id))
                {
                    if (!aem.enabled)
                        continue;
                    string formatted = Format(aem, action.type);
                    if (!parts.Contains(formatted))
                        parts.Add(formatted);
                }
                if (parts.Count > 0)
                {
                    sb.AppendLine("  " + Label(action) + ": " + string.Join(", ", parts));
                    written++;
                }
            }
            return written;
        }

        /// <summary>
        /// The element's display name, plus axis direction for axis actions. Rewired's
        /// elementIdentifierName already folds in any modifier prefix (e.g. "Ctrl + 1"),
        /// so modifierKeyN is intentionally not re-applied here.
        /// </summary>
        private static string Format(ActionElementMap aem, InputActionType actionType)
        {
            string s = aem.elementIdentifierName;
            if (actionType == InputActionType.Axis)
                s += " [" + aem.axisContribution + "]";
            return s;
        }

        private static string Label(InputAction action)
        {
            return string.IsNullOrEmpty(action.descriptiveName)
                ? action.name
                : action.descriptiveName;
        }

        private static string Label(InputMapCategory cat)
        {
            return string.IsNullOrEmpty(cat.descriptiveName) ? cat.name : cat.descriptiveName;
        }
    }
}
